WEBVTT

00:00:01.110 --> 00:00:04.260
Now as I explain of course our promise could also fail.

00:00:04.260 --> 00:00:09.430
So what do you think will help me if I rejected and pass fail.

00:00:10.110 --> 00:00:13.830
Do you think we'll now see the Heidrun.

00:00:15.960 --> 00:00:21.480
Well we just don't see anything because that will handle the case that we're successful.

00:00:21.510 --> 00:00:22.370
But we weren't.

00:00:22.470 --> 00:00:23.970
So we don't see that here.

00:00:24.240 --> 00:00:27.830
But I can pass a second parameter to the function.

00:00:27.840 --> 00:00:35.250
Currently I only have one dysfunction but I can also pass a function to handle the error case.

00:00:35.330 --> 00:00:36.630
So like this.

00:00:36.690 --> 00:00:42.120
And then we could simply log error to the console.

00:00:42.120 --> 00:00:43.420
So what do you think we'll now see.

00:00:43.420 --> 00:00:45.970
I had run.

00:00:47.790 --> 00:00:52.370
Well that we see failed after one and a half second because we reject the promise.

00:00:52.410 --> 00:00:59.070
Now of course you could have where you would have some conditional check in your promise to see if you

00:00:59.070 --> 00:01:01.020
want to reject it or not.

00:01:01.020 --> 00:01:07.620
So if you want to actually call the resolve or the reject function because again a good example of your

00:01:07.620 --> 00:01:09.810
way of reaching out to a server.

00:01:10.080 --> 00:01:15.750
Most of the time this should be successful but you would implement both checks to make sure that you

00:01:15.750 --> 00:01:18.550
handle everything correctly and well in your case